// config/config.ts
export const CONFIG = {
  FRONTEND_URL: 'https://sportish.io',
  FRONTEND_WWW_URL: 'https://www.sportish.io',
  // FRONTEND_URL: 'http://localhost:3000',
  API_BASE_URL: 'https://api2.sportish.io',
  // SCORE_API_BASE_URL: 'https://panelapi.deployed.live',
  // API_BASE_URL: 'https://uatapi.deployed.live',
  MAIN_DOMAIN: "sportish.io",
  WWW_DOMAIN: "www.sportish.io",
  API_ENDPOINTS: {
    GET_INIT_DATA: '/admin/menuItem/getInitData',
    GET_SCHEDULED_MATCH_DATA: '/admin/match/liveScheduleMatchV1',
    GET_LIVE_SCHEDULED_MATCH_LIST: '/admin/match/liveScheduleMatch',
    GET_COMPLETE_MATCH_LIST: '/admin/match/completeMatchesList',
    GET_FULL_SCORECARD_BY_ID: '/admin/match/getfullScoreCardByEId',
    GET_FULL_SCORECARD_SIDEBAR: '/admin/match/getMarketByCId',
    GET_COMMENTARY_BY_ID: '/admin/match/getCommentaryByEId',
    GET_CONFIG_DATA: '/api/configData',
    COUNTRY_CODES: '/api/countryCodes',
    SOCIAL_MEDIA: '/admin/socialMedia/all',
    SIGNIN_CLIENT: '/api/signInApp',
    SIGNUP_CLIENT: '/api/signUpApp',
    RESEND_OTP: '/api/otpResend',
    VERIFY_MOBILE: '/api/verifyMobile',
    UPDATE_CLIENT: '/api/updateClient',
    VERIFY_EMAIL: '/api/verifyEmail',
    GET_PHOTO_LIBRARY: "/admin/library/getPhotoLibrary",
    GET_VIDEO_LIBRARY: "/admin/library/getVideoLibrary",
    CLIENT_DETAILS_BY_EMAILID: "/api/clientDetailsByEmailId",
    VERIFY_OTP: '/api/verifyNo',
    FORGOT_PASSWORD: '/api/forgotPassword',
    FORGOT_PASSWORD_VERIFY_OTP: '/api/forgotOtp',
    RESET_PASSWORD: '/api/updatePass',
    PROFILE: '/api/clientById',
    UPDATE_PROFILE: '/api/editClient',
    OTPLESS_VERIFY: "/api/otplessVerify",
    SAVE_DEVICE: "/api/saveDevice",
  },
  // SCORE_API_ENDPOINTS: {
  //   SIGNUP_CLIENT: '/signupClient',
  //   SIGNUP_CLIENT_DETAILS: '/signupClientDetails',
  //   RESEND_OTP: '/resendOtp',
  //   VERIFY_MOBILE: '/verifyMobile',
  //   VERIFY_MOBILE_OTP: '/verifyMobileOtp',
  //   VERIFY_EMAIL: '/verifyEmail',
  //   VERIFY_EMAIL_TOKEN: '/verifyEmailToken',
  //   VERIFY_OTP: '/verifyOtp',
  //   CLIENT_DETAILS_BY_EMAILID: '/clientDetailsByEmailId',
  //   SET_PASSWORD: '/setPassword',
  //   CHANGE_CLIENT_PASSWORD: '/changeClientPassword',
  //   FORGET_PASSWORD: '/forgetPassword',
  //   SIGNIN_CLIENT: '/signinClient',
  //   SIGNOUT_CLIENT: '/signOutClient',
  //   UPDATECLIENT: '/updateClient',
  //   SAVE_DEVICE: '/admin/devices/save',
  //   NOTIFICATION_BY_CLIENTID: '/admin/score/notificationByClient',
  //   NOTIFICATON_MARK_AS_READ: '/admin/score/markRead',
  //   GET_ALL_BANNERS: '/admin/score/getBanners',
  //   GET_BANNER_BY_ID: '/admin/banner/byId',
  //   SAVE_BANNER_VIEWS: '/admin/activityLog/save',
  //   GET_ALL_BLOCKS: '/admin/score/getAllBlock',
  //   GET_ALL_COMMENTARIES: '/admin/score/getLiveCommentaries',
  //   GET_ALL_COMPETITIONS: '/admin/score/getCompetitions',
  //   GET_ALL_CONFIGS: '/admin/score/getConfigs',
  //   GET_ALL_MARKETTYPES_AND_CATEGORIES: '/admin/score/getMarketTypeAndCategory',
  //   SAVE_DOMAIN: '/admin/score/saveDomain',
  //   GET_ALL_SCHEDULE_MATCHES: '/admin/score/scheduleMatchesList',
  //   GET_ALL_LIVE_MATCHES: '/admin/score/liveMatchesList',
  //   GET_ALL_COMPLETED_MATCHES: '/admin/score/completeMatchesList',
  //   GET_FULLSCORE: '/admin/score/fullScorecard',
  //   GET_SQUAD_LIST: '/admin/score/squadList',
  //   GET_PARTNERSHIP_LIST: '/admin/score/partnershipList',
  //   GET_COMMENTARY_SCORE_BY_EID: '/admin/score/getscoreByEId',
  //   GET_MARKETS_BY_CID: '/admin/score/getMarketsByCId',
  //   GET_MENU_ITEMS_LIST: '/admin/score/getmenuItemList',
  //   GET_ALL_PAGES_LIST: '/admin/score/getPagesList',
  //   GET_ALL_MENUTYPES: '/admin/score/getMenutype',
  //   GET_ALL_MENU_ITEMS: '/admin/score/getMenuItem',
  //   GET_ALL_NEWS: '/admin/score/getAllNews',
  //   NEWS_BY_ID: '/admin/news/byId',
  //   SAVE_NEWS_VIEWS: '/admin/activityLog/save',
  //   GET_ALL_PAGES: '/admin/score/getPagesList',
  //   GET_ALL_PAGE_FORMATE: '/admin/score/getPageFormat'
  // },
};
